# Generated by Django 4.0.5 on 2022-06-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fam', models.CharField(max_length=255)),
                ('phone', models.IntegerField(max_length=50)),
            ],
        ),
    ]
