# Generated by Django 4.0.5 on 2022-06-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ajax', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('summa', models.IntegerField(max_length=20)),
                ('summa2', models.IntegerField(max_length=20)),
                ('itogo', models.IntegerField(max_length=20)),
            ],
        ),
    ]
